name: 'Slack Notification'

inputs:
 webhook_url:
   description: 'Slack webhook URL'
   required: true
 message:
   description: 'Custom message text'
   required: true

runs:
  using: "composite"
  steps:
    - uses: slackapi/slack-github-action@v2.0.0
      with:
        webhook-type: incoming-webhook
        webhook: ${{ inputs.webhook_url }}
        payload: |
          {
            "text": "<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.event.repository.name }}>: ${{ inputs.message }}"
          }
