name: "Start Redpanda"
runs:
  using: "composite"
  steps:
    - name: Start Redpanda
      shell: bash
      run: |
        if [[ -d Tests || -d Benchmarks ]]; then
          echo "Starting Redpanda: $(rpk version)"
          if pgrep -f redpanda.yaml; then
            #sudo -u redpanda rpk redpanda stop
            sudo -u redpanda pkill -9 -f redpanda.yaml > /dev/null 2>&1
          fi
          sudo -u redpanda rm -rf /var/lib/redpanda/data/*
          sudo -u redpanda rpk redpanda start --overprovisioned --smp 2 --memory 2G --reserve-memory 0M --check=false --set redpanda.kafka_group_recovery_timeout_ms=5000 --set redpanda.enable_metrics_reporter=false > /tmp/rpk_log 2>&1 &
          echo "REDPANDA_BROKERS=localhost:9092" >> "$GITHUB_ENV"
        fi
