name: "git credential setup"

inputs:
  token:
    description: 'A Github PAT'
    required: true
  ordo-auth-token:
    description: 'Ordo authentication token'
    required: false

runs:
  using: "composite"
  steps:
    - name: Wipe gitconfig Mac
      shell: bash
      if: ${{ runner.os == 'Macos' }}
      run: |
        echo "" > ~/.gitconfig
        echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
        echo BENCHMARK_DISABLE_JEMALLOC=true >> $GITHUB_ENV
        
    - name: Git URL token override
      shell: bash
      run: git config --global url."https://ordo-ci:${{ inputs.token }}@github.com".insteadOf "https://github.com"
      
    - name: netrc setup
      shell: bash
      run: echo "machine api.github.com login ${{ inputs.token }} password x-oauth-basic" > ~/.netrc

    - name: Setup Ordo auth token
      if: ${{ inputs.ordo-auth-token != '' }}
      shell: bash
      run: |
        mkdir -p ~/.config/ordo
        echo '${{ inputs.ordo-auth-token }}' > ~/.config/ordo/auth.json